
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Componenets/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EventHost",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className="  w-[1440px] mx-auto ">

        {children}
        <Footer/>
        </div>
        </body>
    </html>
  );
}
